# Generated by Django 4.1.4 on 2023-01-14 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GestionAchats', '0005_remove_command_total_price_command_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='command',
            name='total_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
