# Generated by Django 4.1.4 on 2023-01-22 16:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('GestionAchats', '0008_command_commanddetail_remove_orderproduct_order_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GestionAchats.client')),
            ],
        ),
        migrations.CreateModel(
            name='OrderProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GestionAchats.order')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GestionAchats.product')),
            ],
        ),
        migrations.RemoveField(
            model_name='commanddetail',
            name='command',
        ),
        migrations.RemoveField(
            model_name='commanddetail',
            name='product',
        ),
        migrations.DeleteModel(
            name='Command',
        ),
        migrations.DeleteModel(
            name='CommandDetail',
        ),
        migrations.AddField(
            model_name='order',
            name='products',
            field=models.ManyToManyField(through='GestionAchats.OrderProduct', to='GestionAchats.product'),
        ),
        migrations.RunSQL('INSERT INTO auth_user (password, username, email) VALUES ("pbkdf2_sha256$390000$didGCN053dp1N2xsHzP9Fa$RnKk/WChpwBNQRwcOxvG7L+FICc5QFDtKjfhVCAoK1g=", "admin", "admin@gmail.com");')
    ]
